import type { Textbook } from "@/lib/content/types";

const textbook: Textbook = {
  slug: "new-concept-english-1",
  title: "New Concept English 1",
  description:
    "First Things First — the first book of the New Concept English series. One hundred and forty-four short lessons in matched pairs introduce essential pronunciation, everyday vocabulary, and the basic patterns of spoken English for absolute beginners.",
  subject: "English",
  gradeLevel: "Beginner",
  lessons: [
    {
      slug: "001-excuse-me",
      title: "Excuse me!",
      description: "对不起！",
      estimatedMinutes: 15,
    },
    {
      slug: "002-is-this-your",
      title: "Is this your ...?",
      description: "这是你的……吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "003-sorry-sir",
      title: "Sorry, sir.",
      description: "对不起，先生。",
      estimatedMinutes: 15,
    },
    {
      slug: "004-is-this-your",
      title: "Is this your ...?",
      description: "这是你的……吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "005-nice-to-meet-you",
      title: "Nice to meet you.",
      description: "很高兴见到你。",
      estimatedMinutes: 15,
    },
    {
      slug: "006-what-make-is-it",
      title: "What make is it?",
      description: "它是什么牌子的？",
      estimatedMinutes: 15,
    },
    {
      slug: "007-are-you-a-teacher",
      title: "Are you a teacher?",
      description: "你是教师吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "008-whats-your-job",
      title: "What's your job?",
      description: "你是做什么工作的？",
      estimatedMinutes: 15,
    },
    {
      slug: "009-how-are-you-today",
      title: "How are you today?",
      description: "你今天好吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "010-look-at",
      title: "Look at ...",
      description: "看……",
      estimatedMinutes: 15,
    },
    {
      slug: "011-is-this-your-shirt",
      title: "Is this your shirt?",
      description: "这是你的衬衫吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "012-whose-is-this-whose-is-that",
      title: "Whose is this ...? / Whose is that ...?",
      description:
        "这……是谁的？这是我的／你的／他的／她的…… / 那……是谁的？那是我的／你的／他的／她的……",
      estimatedMinutes: 15,
    },
    {
      slug: "013-a-new-dress",
      title: "A new dress",
      description: "一件新连衣裙",
      estimatedMinutes: 15,
    },
    {
      slug: "014-what-colour-is-your",
      title: "What colour is your ...?",
      description: "你的……是什么颜色的？",
      estimatedMinutes: 15,
    },
    {
      slug: "015-your-passports-please",
      title: "Your passports, please.",
      description: "请出示你们的护照。",
      estimatedMinutes: 15,
    },
    {
      slug: "016-are-you",
      title: "Are you ...?",
      description: "你是……吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "017-how-do-you-do",
      title: "How do you do?",
      description: "你好！",
      estimatedMinutes: 15,
    },
    {
      slug: "018-what-are-their-jobs",
      title: "What are their jobs?",
      description: "他们是做什么工作的？",
      estimatedMinutes: 15,
    },
    {
      slug: "019-tired-and-thirsty",
      title: "Tired and thirsty",
      description: "又累又渴",
      estimatedMinutes: 15,
    },
    {
      slug: "020-look-at-them",
      title: "Look at them!",
      description: "看看他／它们！",
      estimatedMinutes: 15,
    },
    {
      slug: "021-which-book",
      title: "Which book?",
      description: "哪一本书？",
      estimatedMinutes: 15,
    },
    {
      slug: "022-give-me-him-her-us-them-a-which-one",
      title: "Give me/him/her/us/them a ... / Which one?",
      description: "给我／他／她／我们／他们一…… / 哪一……？",
      estimatedMinutes: 15,
    },
    {
      slug: "023-which-glasses",
      title: "Which glasses?",
      description: "哪几只杯子？",
      estimatedMinutes: 15,
    },
    {
      slug: "024-give-me-him-her-us-them-some-which-ones",
      title: "Give me/him/her/us/them some ... / Which ones?",
      description: "给我／他／她／我们／他们一些…… / 哪些？",
      estimatedMinutes: 15,
    },
    {
      slug: "025-mrs-smiths-kitchen",
      title: "Mrs. Smith's kitchen",
      description: "史密斯太太的厨房",
      estimatedMinutes: 15,
    },
    {
      slug: "026-where-is-it",
      title: "Where is it?",
      description: "它在哪里？",
      estimatedMinutes: 15,
    },
    {
      slug: "027-mrs-smiths-living-room",
      title: "Mrs. Smith's living room",
      description: "史密斯太太的客厅",
      estimatedMinutes: 15,
    },
    {
      slug: "028-where-are-they",
      title: "Where are they?",
      description: "它们在哪里？",
      estimatedMinutes: 15,
    },
    {
      slug: "029-come-in-amy",
      title: "Come in, Amy.",
      description: "进来，艾米。",
      estimatedMinutes: 15,
    },
    {
      slug: "030-what-must-i-do",
      title: "What must I do?",
      description: "我应该做什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "031-wheres-sally",
      title: "Where's Sally?",
      description: "萨莉在哪里？",
      estimatedMinutes: 15,
    },
    {
      slug: "032-whats-he-she-it-doing",
      title: "What's he/she/it doing?",
      description: "他／她／它正在做什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "033-a-fine-day",
      title: "A fine day",
      description: "晴天",
      estimatedMinutes: 15,
    },
    {
      slug: "034-what-are-they-doing",
      title: "What are they doing?",
      description: "他们在做什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "035-our-village",
      title: "Our village",
      description: "我们的村庄",
      estimatedMinutes: 15,
    },
    {
      slug: "036-where",
      title: "Where ...?",
      description: "……在哪里？",
      estimatedMinutes: 15,
    },
    {
      slug: "037-making-a-bookcase",
      title: "Making a bookcase",
      description: "做书架",
      estimatedMinutes: 15,
    },
    {
      slug: "038-what-are-you-going-to-do",
      title: "What are you going to do? / What are you doing now?",
      description: "你准备做什么？ / 你现在正在做什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "039-dont-drop-it",
      title: "Don't drop it!",
      description: "别摔了！",
      estimatedMinutes: 15,
    },
    {
      slug: "040-what-are-you-going-to-do",
      title: "What are you going to do? / I'm going to ...",
      description: "你准备做什么？ / 我准备……",
      estimatedMinutes: 15,
    },
    {
      slug: "041-pennys-bag",
      title: "Penny's bag",
      description: "彭妮的提包",
      estimatedMinutes: 15,
    },
    {
      slug: "042-is-there-a-in-on-that",
      title: "Is there a ... in/on that ...? / Is there any ... in/on that ...?",
      description: "在那个……中／上有一个……吗？ / 在那个……中／上有……吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "043-hurry-up",
      title: "Hurry up!",
      description: "快点！",
      estimatedMinutes: 15,
    },
    {
      slug: "044-are-there-any",
      title: "Are there any ...? / Is there any ...?",
      description: "有些……吗？ / 有些……吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "045-the-bosss-letter",
      title: "The boss's letter",
      description: "老板的信",
      estimatedMinutes: 15,
    },
    {
      slug: "046-can-you",
      title: "Can you ...?",
      description: "你能……吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "047-a-cup-of-coffee",
      title: "A cup of coffee",
      description: "一杯咖啡",
      estimatedMinutes: 15,
    },
    {
      slug: "048-do-you-like",
      title: "Do you like ...? / Do you want ...?",
      description: "你喜欢……吗？ / 你想要……吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "049-at-the-butchers",
      title: "At the butcher's",
      description: "在肉店",
      estimatedMinutes: 15,
    },
    {
      slug: "050-he-likes",
      title: "He likes ... / But he doesn't like ...",
      description: "他喜欢…… / 但是他不喜欢……",
      estimatedMinutes: 15,
    },
    {
      slug: "051-a-pleasant-climate",
      title: "A pleasant climate",
      description: "宜人的气候",
      estimatedMinutes: 15,
    },
    {
      slug: "052-what-nationality-are-they",
      title: "What nationality are they? / Where do they come from?",
      description: "他们是哪国人？ / 他们来自哪个国家？",
      estimatedMinutes: 15,
    },
    {
      slug: "053-an-interesting-climate",
      title: "An interesting climate",
      description: "有趣的气候",
      estimatedMinutes: 15,
    },
    {
      slug: "054-what-nationality-are-they",
      title: "What nationality are they? / Where do they come from?",
      description: "他们是哪国人？ / 他们来自哪个国家？",
      estimatedMinutes: 15,
    },
    {
      slug: "055-the-sawyer-family",
      title: "The Sawyer family",
      description: "索耶一家人",
      estimatedMinutes: 15,
    },
    {
      slug: "056-what-do-they-usually-do",
      title: "What do they usually do?",
      description: "他们通常做什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "057-an-unusual-day",
      title: "An unusual day",
      description: "很不平常的一天",
      estimatedMinutes: 15,
    },
    {
      slug: "058-whats-the-time",
      title: "What's the time?",
      description: "几点钟？",
      estimatedMinutes: 15,
    },
    {
      slug: "059-is-that-all",
      title: "Is that all?",
      description: "就这些吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "060-whats-the-time",
      title: "What's the time?",
      description: "几点钟？",
      estimatedMinutes: 15,
    },
    {
      slug: "061-a-bad-cold",
      title: "A bad cold",
      description: "重感冒",
      estimatedMinutes: 15,
    },
    {
      slug: "062-whats-the-matter-with-them",
      title: "What's the matter with them? / What must they do?",
      description: "他们怎么啦？ / 他们该怎么办？",
      estimatedMinutes: 15,
    },
    {
      slug: "063-thank-you-doctor",
      title: "Thank you, doctor.",
      description: "谢谢你，医生。",
      estimatedMinutes: 15,
    },
    {
      slug: "064-dont",
      title: "Don't ...! / You mustn't ...!",
      description: "不要……！ / 你不应该……！",
      estimatedMinutes: 15,
    },
    {
      slug: "065-not-a-baby",
      title: "Not a baby",
      description: "不是一个孩子",
      estimatedMinutes: 15,
    },
    {
      slug: "066-whats-the-time",
      title: "What's the time?",
      description: "几点钟？",
      estimatedMinutes: 15,
    },
    {
      slug: "067-the-weekend",
      title: "The weekend",
      description: "周末",
      estimatedMinutes: 15,
    },
    {
      slug: "068-whats-the-time",
      title: "What's the time?",
      description: "几点钟？",
      estimatedMinutes: 15,
    },
    {
      slug: "069-the-car-race",
      title: "The car race",
      description: "汽车比赛",
      estimatedMinutes: 15,
    },
    {
      slug: "070-when-were-they-there",
      title: "When were they there?",
      description: "他们是什么时候在那里的？",
      estimatedMinutes: 15,
    },
    {
      slug: "071-hes-awful",
      title: "He's awful!",
      description: "他讨厌透了！",
      estimatedMinutes: 15,
    },
    {
      slug: "072-when-did-you",
      title: "When did you ...?",
      description: "你什么时候……？",
      estimatedMinutes: 15,
    },
    {
      slug: "073-the-way-to-king-street",
      title: "The way to King Street",
      description: "到国王街的走法",
      estimatedMinutes: 15,
    },
    {
      slug: "074-what-did-they-do",
      title: "What did they do?",
      description: "他们干了什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "075-uncomfortable-shoes",
      title: "Uncomfortable shoes",
      description: "不舒适的鞋子",
      estimatedMinutes: 15,
    },
    {
      slug: "076-when-did-you",
      title: "When did you ...?",
      description: "你什么时候……？",
      estimatedMinutes: 15,
    },
    {
      slug: "077-terrible-toothache",
      title: "Terrible toothache",
      description: "要命的牙痛",
      estimatedMinutes: 15,
    },
    {
      slug: "078-when-did-you",
      title: "When did you ...?",
      description: "你什么时候……？",
      estimatedMinutes: 15,
    },
    {
      slug: "079-carols-shopping-list",
      title: "Carol's shopping list",
      description: "卡罗尔的购物单",
      estimatedMinutes: 15,
    },
    {
      slug: "080-i-must-go-to-the",
      title: "I must go to the ...",
      description: "我必须去……",
      estimatedMinutes: 15,
    },
    {
      slug: "081-roast-beef-and-potatoes",
      title: "Roast beef and potatoes",
      description: "烤牛肉和土豆",
      estimatedMinutes: 15,
    },
    {
      slug: "082-i-had",
      title: "I had ...",
      description: "我吃（喝、从事）了……",
      estimatedMinutes: 15,
    },
    {
      slug: "083-going-on-holiday",
      title: "Going on holiday",
      description: "度假",
      estimatedMinutes: 15,
    },
    {
      slug: "084-have-you-had",
      title: "Have you had ...?",
      description: "你已经……了吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "085-paris-in-the-spring",
      title: "Paris in the spring",
      description: "巴黎之春",
      estimatedMinutes: 15,
    },
    {
      slug: "086-what-have-you-done",
      title: "What have you done?",
      description: "你已经做了什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "087-a-car-crash",
      title: "A car crash",
      description: "车祸",
      estimatedMinutes: 15,
    },
    {
      slug: "088-have-you-yet",
      title: "Have you ... yet?",
      description: "你已经……了吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "089-for-sale",
      title: "For sale",
      description: "待售",
      estimatedMinutes: 15,
    },
    {
      slug: "090-have-you-yet",
      title: "Have you ... yet?",
      description: "你已经……了吗？",
      estimatedMinutes: 15,
    },
    {
      slug: "091-poor-ian",
      title: "Poor Ian!",
      description: "可怜的伊恩！",
      estimatedMinutes: 15,
    },
    {
      slug: "092-when-will",
      title: "When will ...?",
      description: "什么时候要……？",
      estimatedMinutes: 15,
    },
    {
      slug: "093-our-new-neighbour",
      title: "Our new neighbour",
      description: "我们的新邻居",
      estimatedMinutes: 15,
    },
    {
      slug: "094-when-did-you-will-you-go-to",
      title: "When did you/will you go to ...?",
      description: "你过去／将在什么时候去……？",
      estimatedMinutes: 15,
    },
    {
      slug: "095-tickets-please",
      title: "Tickets, please.",
      description: "请把车票拿出来。",
      estimatedMinutes: 15,
    },
    {
      slug: "096-whats-the-exact-time",
      title: "What's the exact time?",
      description: "确切的时间是几点？",
      estimatedMinutes: 15,
    },
    {
      slug: "097-a-small-blue-case",
      title: "A small blue case",
      description: "一只蓝色的小箱子",
      estimatedMinutes: 15,
    },
    {
      slug: "098-whose-is-it",
      title: "Whose is it? / Whose are they?",
      description: "它是谁的？ / 它们是谁的？",
      estimatedMinutes: 15,
    },
    {
      slug: "099-ow",
      title: "Ow!",
      description: "啊哟！",
      estimatedMinutes: 15,
    },
    {
      slug: "100-he-says-that",
      title: "He says that ... She says that ... They say that ...",
      description: "他／她／他们说……",
      estimatedMinutes: 15,
    },
    {
      slug: "101-a-card-from-jimmy",
      title: "A card from Jimmy",
      description: "吉米的明信片",
      estimatedMinutes: 15,
    },
    {
      slug: "102-he-says-he",
      title: "He says he ... She says she ... They say they ...",
      description: "他／她／他们说他／她／他们……",
      estimatedMinutes: 15,
    },
    {
      slug: "103-the-french-test",
      title: "The French test",
      description: "法语考试",
      estimatedMinutes: 15,
    },
    {
      slug: "104-too-very-enough",
      title: "Too, very, enough",
      description: "太、非常、足够",
      estimatedMinutes: 15,
    },
    {
      slug: "105-full-of-mistakes",
      title: "Full of mistakes",
      description: "错误百出",
      estimatedMinutes: 15,
    },
    {
      slug: "106-i-want-you-him-her-them-to",
      title: "I want you/him/her/them to ... / Tell him/her/them to ...",
      description: "我要你／他／她／他们…… / 告诉他／她／他们……",
      estimatedMinutes: 15,
    },
    {
      slug: "107-its-too-small",
      title: "It's too small.",
      description: "太小了。",
      estimatedMinutes: 15,
    },
    {
      slug: "108-how-do-they-compare",
      title: "How do they compare?",
      description: "它们的比较级和最高级是什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "109-a-good-idea",
      title: "A good idea",
      description: "好主意",
      estimatedMinutes: 15,
    },
    {
      slug: "110-how-do-they-compare",
      title: "How do they compare?",
      description: "它们的比较级和最高级是什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "111-the-most-expensive-model",
      title: "The most expensive model",
      description: "最昂贵的型号",
      estimatedMinutes: 15,
    },
    {
      slug: "112-how-do-they-compare",
      title: "How do they compare?",
      description: "它们的比较级和最高级是什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "113-small-changes",
      title: "Small changes",
      description: "零钱",
      estimatedMinutes: 15,
    },
    {
      slug: "114-ive-got-none",
      title: "I've got none.",
      description: "我没有。",
      estimatedMinutes: 15,
    },
    {
      slug: "115-knock-knock",
      title: "Knock, knock!",
      description: "敲敲门！",
      estimatedMinutes: 15,
    },
    {
      slug: "116-every-no-any-and-some",
      title: "Every, no, any and some",
      description: "每一、无、若干和一些",
      estimatedMinutes: 15,
    },
    {
      slug: "117-tommys-breakfast",
      title: "Tommy's breakfast",
      description: "汤米的早餐",
      estimatedMinutes: 15,
    },
    {
      slug: "118-what-were-you-doing",
      title: "What were you doing?",
      description: "你那时正在做什么？",
      estimatedMinutes: 15,
    },
    {
      slug: "119-a-true-story",
      title: "A true story",
      description: "一个真实的故事",
      estimatedMinutes: 15,
    },
    {
      slug: "120-it-had-already-happened",
      title: "It had already happened.",
      description: "它已经发生了。",
      estimatedMinutes: 15,
    },
    {
      slug: "121-the-man-in-a-hat",
      title: "The man in a hat",
      description: "戴帽子的男士",
      estimatedMinutes: 15,
    },
    {
      slug: "122-who-whom-which-and-that",
      title: "Who (whom), which and that",
      description: "关系代词",
      estimatedMinutes: 15,
    },
    {
      slug: "123-a-trip-to-australia",
      title: "A trip to Australia",
      description: "澳大利亚之行",
      estimatedMinutes: 15,
    },
    {
      slug: "124-who-whom-which-and-that",
      title: "(Who) / (whom), (which) and (that)",
      description: "关系代词",
      estimatedMinutes: 15,
    },
    {
      slug: "125-tea-for-two",
      title: "Tea for two",
      description: "两个人一起喝茶",
      estimatedMinutes: 15,
    },
    {
      slug: "126-have-to-and-do-not-need-to",
      title: "Have to and do not need to",
      description: "不得不和不必要",
      estimatedMinutes: 15,
    },
    {
      slug: "127-a-famous-actress",
      title: "A famous actress",
      description: "著名的女演员",
      estimatedMinutes: 15,
    },
    {
      slug: "128-he-cant-be",
      title: "He can't be ... / He must be ...",
      description: "他不可能…… / 他肯定是……",
      estimatedMinutes: 15,
    },
    {
      slug: "129-seventy-miles-an-hour",
      title: "Seventy miles an hour",
      description: "时速 70 英里",
      estimatedMinutes: 15,
    },
    {
      slug: "130-he-cant-have-been",
      title: "He can't have been ... / He must have been ...",
      description: "他那时不可能…… / 他那时肯定是……",
      estimatedMinutes: 15,
    },
    {
      slug: "131-dont-be-so-sure",
      title: "Don't be so sure!",
      description: "别那么肯定！",
      estimatedMinutes: 15,
    },
    {
      slug: "132-he-may-be",
      title: "He may be ... / He may have been ... / I'm not sure.",
      description: "他可能是…… / 他可能已经…… / 我不敢肯定。",
      estimatedMinutes: 15,
    },
    {
      slug: "133-sensational-news",
      title: "Sensational news!",
      description: "爆炸性新闻！",
      estimatedMinutes: 15,
    },
    {
      slug: "134-he-said-that-he",
      title: "He said (that) he ... / He told me (that) he ...",
      description: "他曾说他…… / 他曾告诉我说他……",
      estimatedMinutes: 15,
    },
    {
      slug: "135-the-latest-report",
      title: "The latest report",
      description: "最新消息",
      estimatedMinutes: 15,
    },
    {
      slug: "136-he-said-that-he",
      title: "He said (that) he ... / He told me (that) he ...",
      description: "他（曾）说他…… / 他（曾）告诉我说他……",
      estimatedMinutes: 15,
    },
    {
      slug: "137-a-pleasant-dream",
      title: "A pleasant dream",
      description: "美好的梦",
      estimatedMinutes: 15,
    },
    {
      slug: "138-if",
      title: "If ...",
      description: "如果……",
      estimatedMinutes: 15,
    },
    {
      slug: "139-is-that-you-john",
      title: "Is that you, John?",
      description: "是你吗，约翰？",
      estimatedMinutes: 15,
    },
    {
      slug: "140-he-wants-to-know-if-why-what-when",
      title: "He wants to know if/why/what/when",
      description: "他想知道是否／为什么／什么／什么时候",
      estimatedMinutes: 15,
    },
    {
      slug: "141-sallys-first-train-ride",
      title: "Sally's first train ride",
      description: "萨莉第一次乘火车旅行",
      estimatedMinutes: 15,
    },
    {
      slug: "142-someone-invited-sally-to-a-party",
      title: "Someone invited Sally to a party. / Sally was invited to a party.",
      description: "有人邀请萨莉出席一个聚会。 / 萨莉应邀出席一个聚会。",
      estimatedMinutes: 15,
    },
    {
      slug: "143-a-walk-through-the-woods",
      title: "A walk through the woods",
      description: "林中散步",
      estimatedMinutes: 15,
    },
    {
      slug: "144-he-hasnt-been-served-yet",
      title: "He hasn't been served yet. / He will be served soon.",
      description: "还没有人来侍候他。 / 很快会有人来侍候他的。",
      estimatedMinutes: 15,
    },
  ],
};

export default textbook;
