import type { Textbook } from "@/lib/content/types";

const textbook: Textbook = {
  slug: "new-concept-english-2",
  title: "New Concept English 2",
  description:
    "Practice and Progress — the second book of the New Concept English series. Ninety-six short passages build intermediate reading and listening, with comprehension, structure, and the foundations of writing.",
  subject: "English",
  gradeLevel: "Intermediate",
  lessons: [
    {
      slug: "01-a-private-conversation",
      title: "A private conversation",
      description: "私人谈话",
      estimatedMinutes: 20,
    },
    {
      slug: "02-breakfast-or-lunch",
      title: "Breakfast or lunch?",
      description: "早餐还是午餐？",
      estimatedMinutes: 20,
    },
    {
      slug: "03-please-send-me-a-card",
      title: "Please send me a card",
      description: "请给我寄一张明信片",
      estimatedMinutes: 20,
    },
    {
      slug: "04-an-exciting-trip",
      title: "An exciting trip",
      description: "激动人心的旅行",
      estimatedMinutes: 20,
    },
    {
      slug: "05-no-wrong-numbers",
      title: "No wrong numbers",
      description: "无错号之虞",
      estimatedMinutes: 20,
    },
    {
      slug: "06-percy-buttons",
      title: "Percy Buttons",
      description: "珀西·巴顿斯",
      estimatedMinutes: 20,
    },
    {
      slug: "07-too-late",
      title: "Too late",
      description: "为时太晚",
      estimatedMinutes: 20,
    },
    {
      slug: "08-the-best-and-the-worst",
      title: "The best and the worst",
      description: "最好的和最差的",
      estimatedMinutes: 20,
    },
    {
      slug: "09-a-cold-welcome",
      title: "A cold welcome",
      description: "冷遇",
      estimatedMinutes: 20,
    },
    {
      slug: "10-not-for-jazz",
      title: "Not for jazz",
      description: "不适于演奏爵士乐",
      estimatedMinutes: 20,
    },
    {
      slug: "11-one-good-turn-deserves-another",
      title: "One good turn deserves another",
      description: "礼尚往来",
      estimatedMinutes: 20,
    },
    {
      slug: "12-goodbye-and-good-luck",
      title: "Goodbye and good luck",
      description: "再见，一路顺风",
      estimatedMinutes: 20,
    },
    {
      slug: "13-the-greenwood-boys",
      title: "The Greenwood Boys",
      description: "绿林少年",
      estimatedMinutes: 20,
    },
    {
      slug: "14-do-you-speak-english",
      title: "Do you speak English?",
      description: "你会讲英语吗？",
      estimatedMinutes: 20,
    },
    {
      slug: "15-good-news",
      title: "Good news",
      description: "佳音",
      estimatedMinutes: 20,
    },
    {
      slug: "16-a-polite-request",
      title: "A polite request",
      description: "彬彬有礼的要求",
      estimatedMinutes: 20,
    },
    {
      slug: "17-always-young",
      title: "Always young",
      description: "青春常驻",
      estimatedMinutes: 20,
    },
    {
      slug: "18-he-often-does-this",
      title: "He often does this!",
      description: "他经常干这种事！",
      estimatedMinutes: 20,
    },
    {
      slug: "19-sold-out",
      title: "Sold out",
      description: "票已售完",
      estimatedMinutes: 20,
    },
    {
      slug: "20-one-man-in-a-boat",
      title: "One man in a boat",
      description: "独坐孤舟",
      estimatedMinutes: 20,
    },
    {
      slug: "21-mad-or-not",
      title: "Mad or not?",
      description: "是不是疯了？",
      estimatedMinutes: 20,
    },
    {
      slug: "22-a-glass-envelope",
      title: "A glass envelope",
      description: "玻璃信封",
      estimatedMinutes: 20,
    },
    {
      slug: "23-a-new-house",
      title: "A new house",
      description: "新居",
      estimatedMinutes: 20,
    },
    {
      slug: "24-it-could-be-worse",
      title: "It could be worse",
      description: "不幸中之万幸",
      estimatedMinutes: 20,
    },
    {
      slug: "25-do-the-english-speak-english",
      title: "Do the English speak English?",
      description: "英国人讲的是英语吗？",
      estimatedMinutes: 20,
    },
    {
      slug: "26-the-best-art-critics",
      title: "The best art critics",
      description: "最佳美术评论家",
      estimatedMinutes: 20,
    },
    {
      slug: "27-a-wet-night",
      title: "A wet night",
      description: "雨夜",
      estimatedMinutes: 20,
    },
    {
      slug: "28-no-parking",
      title: "No parking",
      description: "禁止停车",
      estimatedMinutes: 20,
    },
    {
      slug: "29-taxi",
      title: "Taxi!",
      description: "出租汽车！",
      estimatedMinutes: 20,
    },
    {
      slug: "30-football-or-polo",
      title: "Football or polo?",
      description: "足球还是水球？",
      estimatedMinutes: 20,
    },
    {
      slug: "31-success-story",
      title: "Success story",
      description: "成功者的故事",
      estimatedMinutes: 20,
    },
    {
      slug: "32-shopping-made-easy",
      title: "Shopping made easy",
      description: "购物变得很方便",
      estimatedMinutes: 20,
    },
    {
      slug: "33-out-of-the-darkness",
      title: "Out of the darkness",
      description: "冲出黑暗",
      estimatedMinutes: 20,
    },
    {
      slug: "34-quick-work",
      title: "Quick work",
      description: "破案“神速”",
      estimatedMinutes: 20,
    },
    {
      slug: "35-stop-thief",
      title: "Stop thief!",
      description: "捉贼！",
      estimatedMinutes: 20,
    },
    {
      slug: "36-across-the-channel",
      title: "Across the Channel",
      description: "横渡海峡",
      estimatedMinutes: 20,
    },
    {
      slug: "37-the-olympic-games",
      title: "The Olympic Games",
      description: "奥林匹克运动会",
      estimatedMinutes: 20,
    },
    {
      slug: "38-everything-except-the-weather",
      title: "Everything except the weather",
      description: "唯独没有考虑到天气",
      estimatedMinutes: 20,
    },
    {
      slug: "39-am-i-all-right",
      title: "Am I all right?",
      description: "我是否痊愈？",
      estimatedMinutes: 20,
    },
    {
      slug: "40-food-and-talk",
      title: "Food and talk",
      description: "进餐与交谈",
      estimatedMinutes: 20,
    },
    {
      slug: "41-do-you-call-that-a-hat",
      title: "Do you call that a hat?",
      description: "你把那个叫帽子吗？",
      estimatedMinutes: 20,
    },
    {
      slug: "42-not-very-musical",
      title: "Not very musical",
      description: "并非很懂音乐",
      estimatedMinutes: 20,
    },
    {
      slug: "43-over-the-south-pole",
      title: "Over the South Pole",
      description: "飞越南极",
      estimatedMinutes: 20,
    },
    {
      slug: "44-through-the-forest",
      title: "Through the forest",
      description: "穿过森林",
      estimatedMinutes: 20,
    },
    {
      slug: "45-a-clear-conscience",
      title: "A clear conscience",
      description: "问心无愧",
      estimatedMinutes: 20,
    },
    {
      slug: "46-expensive-and-uncomfortable",
      title: "Expensive and uncomfortable",
      description: "既昂贵又受罪",
      estimatedMinutes: 20,
    },
    {
      slug: "47-a-thirsty-ghost",
      title: "A thirsty ghost",
      description: "嗜酒的鬼魂",
      estimatedMinutes: 20,
    },
    {
      slug: "48-did-you-want-to-tell-me-something",
      title: "Did you want to tell me something?",
      description: "你想对我说什么吗？",
      estimatedMinutes: 20,
    },
    {
      slug: "49-the-end-of-a-dream",
      title: "The end of a dream",
      description: "美梦告终",
      estimatedMinutes: 20,
    },
    {
      slug: "50-taken-for-a-ride",
      title: "Taken for a ride",
      description: "乘车兜风",
      estimatedMinutes: 20,
    },
    {
      slug: "51-reward-for-virtue",
      title: "Reward for virtue",
      description: "对美德的奖赏",
      estimatedMinutes: 20,
    },
    {
      slug: "52-a-pretty-carpet",
      title: "A pretty carpet",
      description: "漂亮的地毯",
      estimatedMinutes: 20,
    },
    {
      slug: "53-hot-snake",
      title: "Hot snake",
      description: "触电的蛇",
      estimatedMinutes: 20,
    },
    {
      slug: "54-sticky-fingers",
      title: "Sticky fingers",
      description: "粘糊的手指",
      estimatedMinutes: 20,
    },
    {
      slug: "55-not-a-gold-mine",
      title: "Not a gold mine",
      description: "并非金矿",
      estimatedMinutes: 20,
    },
    {
      slug: "56-faster-than-sound",
      title: "Faster than sound!",
      description: "比声音还快！",
      estimatedMinutes: 20,
    },
    {
      slug: "57-can-i-help-you-madam",
      title: "Can I help you, madam?",
      description: "你要买什么，夫人？",
      estimatedMinutes: 20,
    },
    {
      slug: "58-a-blessing-in-disguise",
      title: "A blessing in disguise?",
      description: "是因祸得福吗？",
      estimatedMinutes: 20,
    },
    {
      slug: "59-in-or-out",
      title: "In or out?",
      description: "进来还是出去？",
      estimatedMinutes: 20,
    },
    {
      slug: "60-the-future",
      title: "The future",
      description: "卜算未来",
      estimatedMinutes: 20,
    },
    {
      slug: "61-trouble-with-the-hubble",
      title: "Trouble with the Hubble",
      description: "哈勃望远镜的困境",
      estimatedMinutes: 20,
    },
    {
      slug: "62-after-the-fire",
      title: "After the fire",
      description: "大火之后",
      estimatedMinutes: 20,
    },
    {
      slug: "63-she-was-not-amused",
      title: "She was not amused",
      description: "她并不觉得好笑",
      estimatedMinutes: 20,
    },
    {
      slug: "64-the-channel-tunnel",
      title: "The Channel Tunnel",
      description: "海峡隧道",
      estimatedMinutes: 20,
    },
    {
      slug: "65-jumbo-versus-the-police",
      title: "Jumbo versus the police",
      description: "小象对警察",
      estimatedMinutes: 20,
    },
    {
      slug: "66-sweet-as-honey",
      title: "Sweet as honey!",
      description: "像蜜一样甜！",
      estimatedMinutes: 20,
    },
    {
      slug: "67-volcanoes",
      title: "Volcanoes",
      description: "火山",
      estimatedMinutes: 20,
    },
    {
      slug: "68-persistent",
      title: "Persistent",
      description: "纠缠不休",
      estimatedMinutes: 20,
    },
    {
      slug: "69-but-not-murder",
      title: "But not murder!",
      description: "并非谋杀！",
      estimatedMinutes: 20,
    },
    {
      slug: "70-red-for-danger",
      title: "Red for danger",
      description: "危险的红色",
      estimatedMinutes: 20,
    },
    {
      slug: "71-a-famous-clock",
      title: "A famous clock",
      description: "一个著名的大钟",
      estimatedMinutes: 20,
    },
    {
      slug: "72-a-car-called-bluebird",
      title: "A car called Bluebird",
      description: "“蓝鸟”汽车",
      estimatedMinutes: 20,
    },
    {
      slug: "73-the-record-holder",
      title: "The record-holder",
      description: "纪录保持者",
      estimatedMinutes: 20,
    },
    {
      slug: "74-out-of-the-limelight",
      title: "Out of the limelight",
      description: "舞台之外",
      estimatedMinutes: 20,
    },
    {
      slug: "75-sos",
      title: "SOS",
      description: "呼救信号",
      estimatedMinutes: 20,
    },
    {
      slug: "76-april-fools-day",
      title: "April Fools' Day",
      description: "愚人节",
      estimatedMinutes: 20,
    },
    {
      slug: "77-a-successful-operation",
      title: "A successful operation",
      description: "一例成功的手术",
      estimatedMinutes: 20,
    },
    {
      slug: "78-the-last-one",
      title: "The last one?",
      description: "最后一枝吗？",
      estimatedMinutes: 20,
    },
    {
      slug: "79-by-air",
      title: "By air",
      description: "乘飞机",
      estimatedMinutes: 20,
    },
    {
      slug: "80-the-crystal-palace",
      title: "The Crystal Palace",
      description: "水晶宫",
      estimatedMinutes: 20,
    },
    {
      slug: "81-escape",
      title: "Escape",
      description: "脱逃",
      estimatedMinutes: 20,
    },
    {
      slug: "82-monster-or-fish",
      title: "Monster or fish?",
      description: "是妖还是鱼？",
      estimatedMinutes: 20,
    },
    {
      slug: "83-after-the-elections",
      title: "After the elections",
      description: "大选之后",
      estimatedMinutes: 20,
    },
    {
      slug: "84-on-strike",
      title: "On strike",
      description: "罢工",
      estimatedMinutes: 20,
    },
    {
      slug: "85-never-too-old-to-learn",
      title: "Never too old to learn",
      description: "活到老学到老",
      estimatedMinutes: 20,
    },
    {
      slug: "86-out-of-control",
      title: "Out of control",
      description: "失控",
      estimatedMinutes: 20,
    },
    {
      slug: "87-a-perfect-alibi",
      title: "A perfect alibi",
      description: "极好的不在犯罪现场的证据",
      estimatedMinutes: 20,
    },
    {
      slug: "88-trapped-in-a-mine",
      title: "Trapped in a mine",
      description: "困在矿井里",
      estimatedMinutes: 20,
    },
    {
      slug: "89-a-slip-of-the-tongue",
      title: "A slip of the tongue",
      description: "口误",
      estimatedMinutes: 20,
    },
    {
      slug: "90-whats-for-supper",
      title: "What's for supper?",
      description: "晚餐吃什么？",
      estimatedMinutes: 20,
    },
    {
      slug: "91-three-men-in-a-basket",
      title: "Three men in a basket",
      description: "三人同篮",
      estimatedMinutes: 20,
    },
    {
      slug: "92-asking-for-trouble",
      title: "Asking for trouble",
      description: "自找麻烦",
      estimatedMinutes: 20,
    },
    {
      slug: "93-a-noble-gift",
      title: "A noble gift",
      description: "崇高的礼物",
      estimatedMinutes: 20,
    },
    {
      slug: "94-future-champions",
      title: "Future champions",
      description: "未来的冠军",
      estimatedMinutes: 20,
    },
    {
      slug: "95-a-fantasy",
      title: "A fantasy",
      description: "纯属虚构",
      estimatedMinutes: 20,
    },
    {
      slug: "96-the-dead-return",
      title: "The dead return",
      description: "亡灵返乡",
      estimatedMinutes: 20,
    },
  ],
};

export default textbook;
