import type { Textbook } from "@/lib/content/types";

const textbook: Textbook = {
  slug: "new-concept-english-3",
  title: "New Concept English 3",
  description:
    "Developing Skills — the third book of the New Concept English series, with longer passages for advanced reading, writing, and discussion.",
  subject: "English",
  gradeLevel: "Advanced",
  lessons: [
    {
      slug: "01-a-puma-at-large",
      title: "A puma at large",
      description: "逃遁的美洲狮",
      estimatedMinutes: 25,
    },
    {
      slug: "02-thirteen-equals-one",
      title: "Thirteen equals one",
      description: "十三等于一",
      estimatedMinutes: 25,
    },
    {
      slug: "03-an-unknown-goddess",
      title: "An unknown goddess",
      description: "无名女神",
      estimatedMinutes: 25,
    },
    {
      slug: "04-the-double-life-of-alfred-bloggs",
      title: "The double life of Alfred Bloggs",
      description: "阿尔弗雷德·布洛格斯的双重生活",
      estimatedMinutes: 25,
    },
    {
      slug: "05-the-facts",
      title: "The facts",
      description: "确切数字",
      estimatedMinutes: 25,
    },
    {
      slug: "06-smash-and-grab",
      title: "Smash-and-grab",
      description: "砸橱窗抢劫",
      estimatedMinutes: 25,
    },
    {
      slug: "07-mutilated-ladies",
      title: "Mutilated ladies",
      description: "残钞鉴别组",
      estimatedMinutes: 25,
    },
    {
      slug: "08-a-famous-monastery",
      title: "A famous monastery",
      description: "著名的修道院",
      estimatedMinutes: 25,
    },
    {
      slug: "09-flying-cats",
      title: "Flying cats",
      description: "飞猫",
      estimatedMinutes: 25,
    },
    {
      slug: "10-the-loss-of-the-titanic",
      title: "The loss of the Titanic",
      description: "“泰坦尼克”号的沉没",
      estimatedMinutes: 25,
    },
    {
      slug: "11-not-guilty",
      title: "Not guilty",
      description: "无罪",
      estimatedMinutes: 25,
    },
    {
      slug: "12-life-on-a-desert-island",
      title: "Life on a desert island",
      description: "荒岛生活",
      estimatedMinutes: 25,
    },
    {
      slug: "13-its-only-me",
      title: "'It's only me'",
      description: "“是我，别害怕”",
      estimatedMinutes: 25,
    },
    {
      slug: "14-a-noble-gangster",
      title: "A noble gangster",
      description: "贵族歹徒",
      estimatedMinutes: 25,
    },
    {
      slug: "15-fifty-pence-worth-of-trouble",
      title: "Fifty pence worth of trouble",
      description: "五十便士的麻烦",
      estimatedMinutes: 25,
    },
    {
      slug: "16-mary-had-a-little-lamb",
      title: "Mary had a little lamb",
      description: "玛丽有一头小羔羊",
      estimatedMinutes: 25,
    },
    {
      slug: "17-the-longest-suspension-bridge-in-the-world",
      title: "The longest suspension bridge in the world",
      description: "世界上最长的吊桥",
      estimatedMinutes: 25,
    },
    {
      slug: "18-electric-currents-in-modern-art",
      title: "Electric currents in modern art",
      description: "现代艺术中的电流",
      estimatedMinutes: 25,
    },
    {
      slug: "19-a-very-dear-cat",
      title: "A very dear cat",
      description: "一只贵重的宝贝猫",
      estimatedMinutes: 25,
    },
    {
      slug: "20-pioneer-pilots",
      title: "Pioneer pilots",
      description: "飞行员的先驱",
      estimatedMinutes: 25,
    },
    {
      slug: "21-daniel-mendoza",
      title: "Daniel Mendoza",
      description: "丹尼尔·门多萨",
      estimatedMinutes: 25,
    },
    {
      slug: "22-by-heart",
      title: "By heart",
      description: "熟记台词",
      estimatedMinutes: 25,
    },
    {
      slug: "23-one-mans-meat-is-another-mans-poison",
      title: "One man's meat is another man's poison",
      description: "各有所爱",
      estimatedMinutes: 25,
    },
    {
      slug: "24-a-skeleton-in-the-cupboard",
      title: "A skeleton in the cupboard",
      description: "“家丑”",
      estimatedMinutes: 25,
    },
    {
      slug: "25-the-cutty-sark",
      title: "The Cutty Sark",
      description: "“卡蒂萨克”号帆船",
      estimatedMinutes: 25,
    },
    {
      slug: "26-wanted-a-large-biscuit-tin",
      title: "Wanted: a large biscuit tin",
      description: "征购大饼干筒",
      estimatedMinutes: 25,
    },
    {
      slug: "27-nothing-to-sell-and-nothing-to-buy",
      title: "Nothing to sell and nothing to buy",
      description: "不卖也不买",
      estimatedMinutes: 25,
    },
    {
      slug: "28-five-pounds-too-dear",
      title: "Five pounds too dear",
      description: "五镑也太贵",
      estimatedMinutes: 25,
    },
    {
      slug: "29-funny-or-not",
      title: "Funny or not?",
      description: "是否可笑？",
      estimatedMinutes: 25,
    },
    {
      slug: "30-the-death-of-a-ghost",
      title: "The death of a ghost",
      description: "幽灵之死",
      estimatedMinutes: 25,
    },
    {
      slug: "31-a-lovable-eccentric",
      title: "A lovable eccentric",
      description: "可爱的怪人",
      estimatedMinutes: 25,
    },
    {
      slug: "32-a-lost-ship",
      title: "A lost ship",
      description: "一艘沉船",
      estimatedMinutes: 25,
    },
    {
      slug: "33-a-day-to-remember",
      title: "A day to remember",
      description: "难忘的一天",
      estimatedMinutes: 25,
    },
    {
      slug: "34-a-happy-discovery",
      title: "A happy discovery",
      description: "幸运的发现",
      estimatedMinutes: 25,
    },
    {
      slug: "35-justice-was-done",
      title: "Justice was done",
      description: "伸张正义",
      estimatedMinutes: 25,
    },
    {
      slug: "36-a-chance-in-a-million",
      title: "A chance in a million",
      description: "百万分之一的机遇",
      estimatedMinutes: 25,
    },
    {
      slug: "37-the-westhaven-express",
      title: "The Westhaven Express",
      description: "开往威斯特海温的快车",
      estimatedMinutes: 25,
    },
    {
      slug: "38-the-first-calendar",
      title: "The first calendar",
      description: "最早的日历",
      estimatedMinutes: 25,
    },
    {
      slug: "39-nothing-to-worry-about",
      title: "Nothing to worry about",
      description: "不必担心",
      estimatedMinutes: 25,
    },
    {
      slug: "40-whos-who",
      title: "Who's who",
      description: "真假难辨",
      estimatedMinutes: 25,
    },
    {
      slug: "41-illusions-of-pastoral-peace",
      title: "Illusions of pastoral peace",
      description: "宁静田园生活的遐想",
      estimatedMinutes: 25,
    },
    {
      slug: "42-modern-cavemen",
      title: "Modern cavemen",
      description: "现代洞穴人",
      estimatedMinutes: 25,
    },
    {
      slug: "43-fully-insured",
      title: "Fully insured",
      description: "全保险",
      estimatedMinutes: 25,
    },
    {
      slug: "44-speed-and-comfort",
      title: "Speed and comfort",
      description: "又快捷又舒适",
      estimatedMinutes: 25,
    },
    {
      slug: "45-the-power-of-the-press",
      title: "The power of the press",
      description: "新闻报道的威力",
      estimatedMinutes: 25,
    },
    {
      slug: "46-do-it-yourself",
      title: "Do it yourself",
      description: "自己动手",
      estimatedMinutes: 25,
    },
    {
      slug: "47-too-high-a-price",
      title: "Too high a price?",
      description: "代价太高？",
      estimatedMinutes: 25,
    },
    {
      slug: "48-the-silent-village",
      title: "The silent village",
      description: "沉默的村庄",
      estimatedMinutes: 25,
    },
    {
      slug: "49-the-ideal-servant",
      title: "The ideal servant",
      description: "理想的仆人",
      estimatedMinutes: 25,
    },
    {
      slug: "50-new-year-resolutions",
      title: "New Year resolutions",
      description: "新年的决心",
      estimatedMinutes: 25,
    },
    {
      slug: "51-predicting-the-future",
      title: "Predicting the future",
      description: "预测未来",
      estimatedMinutes: 25,
    },
    {
      slug: "52-mud-is-mud",
      title: "Mud is mud",
      description: "实事求是",
      estimatedMinutes: 25,
    },
    {
      slug: "53-in-the-public-interest",
      title: "In the public interest",
      description: "为了公众的利益",
      estimatedMinutes: 25,
    },
    {
      slug: "54-instinct-or-cleverness",
      title: "Instinct or cleverness?",
      description: "是本能还是机智",
      estimatedMinutes: 25,
    },
    {
      slug: "55-from-the-earth-greetings",
      title: "From the earth: Greetings",
      description: "来自地球的问候",
      estimatedMinutes: 25,
    },
    {
      slug: "56-our-neighbour-the-river",
      title: "Our neighbour, the river",
      description: "河流，我们的邻居",
      estimatedMinutes: 25,
    },
    {
      slug: "57-back-in-the-old-country",
      title: "Back in the old country",
      description: "重返故里",
      estimatedMinutes: 25,
    },
    {
      slug: "58-a-spot-of-bother",
      title: "A spot of bother",
      description: "一点儿小麻烦",
      estimatedMinutes: 25,
    },
    {
      slug: "59-collecting",
      title: "Collecting",
      description: "收藏",
      estimatedMinutes: 25,
    },
    {
      slug: "60-too-early-and-too-late",
      title: "Too early and too late",
      description: "太早和太晚",
      estimatedMinutes: 25,
    },
  ],
};

export default textbook;
